# This file is a template, and might need editing before it works on your project.
# Explanation on the scripts:
# https://gitlab.com/gitlab-examples/kubernetes-deploy/blob/master/README.md
image: registry.platformserviceaccount.com/lush-soa/dev-ops/soa-cicd:latest

variables:
  # Application deployment domain
  KUBE_DOMAIN: platformserviceaccount.com
  KUBE_DOMAIN_PROD: cloudserviceaccount.com
  AGGREGATOR_DOMAIN_PREFIX: agg


stages:
  - pre-ci-review
  - pre-ci-staging
  - pre-ci-production
  - build
  - review
  - staging
  - production
  - cleanup
  - post-cd-review
  - post-cd-staging
  - post-cd-production

build:
  stage: build
  script:
    - command java-aggregator-build
  only:
    - branches
    - tags

pre-ci-review:
  stage: pre-ci-review
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  script:
    - command pre-ci
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  only:
    - branches
  except:
    - master

pre-ci-staging:
  stage: pre-ci-staging
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  script:
    - command pre-ci
  environment:
    name: staging
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  only:
    - master
    - tags

pre-ci-production:
  stage: pre-ci-production
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME.$KUBE_DOMAIN_PROD
  script:
    - command pre-ci
  environment:
    name: production
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME.$KUBE_DOMAIN_PROD
  when: manual
  only:
    - master
    - tags
    
review:
  stage: review
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  script:
    - command java-aggregator-deploy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
    on_stop: cleanup
  only:
    - branches
  except:
    - master

staging:
  stage: staging
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  script:
    - command java-aggregator-deploy
  environment:
    name: staging
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  only:
    - master
    - tags

production:
  stage: production
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME.$KUBE_DOMAIN_PROD
  script:
    - command java-aggregator-deploy
  environment:
    name: production
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME.$KUBE_DOMAIN_PROD
  when: manual
  only:
    - master
    - tags

cleanup:
  stage: cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - command java-aggregator-destroy
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  only:
    - branches
  except:
    - master

post-cd-review:
  stage: post-cd-review
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  script:
    - command post-cd
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$KUBE_DOMAIN
  only:
    - branches
  except:
    - master

post-cd-staging:
  stage: post-cd-staging
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  script:
    - command post-cd
  environment:
    name: staging
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME-staging.$KUBE_DOMAIN
  only:
    - master
    - tags

post-cd-production:
  stage: post-cd-production
  variables:
    CI_ENVIRONMENT_URL: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME.$KUBE_DOMAIN_PROD
  script:
    - command post-cd
  environment:
    name: production
    url: http://$AGGREGATOR_DOMAIN_PREFIX-$CI_PROJECT_NAME.$KUBE_DOMAIN_PROD
  when: manual
  only:
    - master
    - tags