image: registry.platformserviceaccount.com/lush-soa/dev-ops/soa-cicd:stable

variables:
  KUBE_DOMAIN: platformserviceaccount.com
stages:
  - build

# Stages for golang
docker-master-build:
  stage: build
  script:
    - command base-build-docker
  only:
    - master

docker-tag-build:
  stage: build
  script:
    - command base-build-docker
  only:
    - tags

helm-master-build:
  stage: build
  script:
    - command base-build-helm
  only:
    - master

helm-tag-build:
  stage: build
  script:
    - command base-build-helm
  only:
    - tags
