# Default values for golang.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceName: "java-aggregator"

dbHost: "127.0.0.1"

dbUser: "proxyUser"

dbPass: ""

redisHost: "127.0.0.1"

replicas: 3

pullPolicy: "Always"

projectZone: "europe-west1"

projectId: "lush-global-soa-architecture"

podAutoscaling: 1

developmentVolumeMapping: 0

serviceIngress: 1

chartVersion: "9.0.0-stable"

cloudSql: 1

serviceEnvironment: "staging"

serviceTag: ""

# Additional environment variables required by the service.
# Specied in the pattern - name: value. Example:
#
# envVars:
#   A_NEW_VARIABLE: test
#   ANOTHER_VARIABLE: wibble
envVars:

# Additional artisan commands that need to run as pods.
#
# extraCommands:
#   - name: "My Command"
#     command: script.sh
#     args: ["--verbose"]
extraCommands:
