apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  namespace: {{.Values.serviceNamespace}}
  labels:
    app: {{.Values.ciEnvironmentSlug}}
    pipeline_id: "{{.Values.ciPipelineId}}"
    build_id: "{{.Values.ciBuildId}}"
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
  selector:
    app: {{.Values.ciEnvironmentSlug}}
